CREATE SCHEMA "producaosia";
--> statement-breakpoint
CREATE TABLE "producaosia"."agrupamentos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "producaosia"."agrupamentos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cod_proced" text NOT NULL,
	"cod_cbo" text NOT NULL,
	"natureza" text NOT NULL,
	"especialidade" text,
	"nivel_atencao" text NOT NULL,
	CONSTRAINT "chk_agrupamentos_natureza" CHECK (natureza IN (
        'Procedimento',
        'Exame Laboratorial',
        'Exame de Imagem / Diagnóstico',
        'Consulta',
        'Testes Rápidos e POCT',
        'Procedimento Odontológico',
        'Ações Coletivas e Educativas',
        'Ações de Rede e Matriciamento',
        'Acolhimento, Visita e Intervenção Territorial',
        'Materiais e OPMEs'
      )),
	CONSTRAINT "chk_agrupamentos_nivel_atencao" CHECK (nivel_atencao IN (
        'APS', 'ESPECIALIZADA', 'URGENCIA', 'HOSPITALAR',
        'APOIO_DIAGNOSTICO', 'VIGILANCIA', 'TFD', 'CONTEXTUAL'
      ))
);
--> statement-breakpoint
CREATE TABLE "producaosia"."cbo" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "producaosia"."cbo_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cod_cbo" text NOT NULL,
	"descricao" text NOT NULL,
	CONSTRAINT "uq_cbo_cod_cbo" UNIQUE("cod_cbo")
);
--> statement-breakpoint
CREATE TABLE "producaosia"."cbos_aps" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "producaosia"."cbos_aps_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cod_cbo" text NOT NULL,
	"descricao" text,
	CONSTRAINT "uq_cbos_aps_cod_cbo" UNIQUE("cod_cbo")
);
--> statement-breakpoint
CREATE TABLE "producaosia"."estabelecimentos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "producaosia"."estabelecimentos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cod_cnes" text NOT NULL,
	"competencia" date NOT NULL,
	"nome_fantasia" text NOT NULL,
	"cnpj" text,
	"tipo_estabelecimento" text,
	"nivel_atencao" text,
	"status" text,
	"telefone" text,
	"diretor" text,
	"location" text
);
--> statement-breakpoint
CREATE TABLE "producaosia"."nomes_curtos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "producaosia"."nomes_curtos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cod_cnes" text NOT NULL,
	"nome_curto" text NOT NULL,
	"nome_oficial" text,
	CONSTRAINT "uq_nomes_curtos_cod_cnes" UNIQUE("cod_cnes")
);
--> statement-breakpoint
CREATE TABLE "producaosia"."procedimentos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "producaosia"."procedimentos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cod_proced" text NOT NULL,
	"descricao" text NOT NULL,
	CONSTRAINT "uq_procedimentos_cod_proced" UNIQUE("cod_proced")
);
--> statement-breakpoint
CREATE TABLE "producaosia"."producao_sia" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "producaosia"."producao_sia_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cod_cnes" text NOT NULL,
	"competencia" date NOT NULL,
	"cod_proced" text NOT NULL,
	"cod_cbo" text NOT NULL,
	"qtd_apresentada" integer NOT NULL,
	"qtd_aprovada" integer NOT NULL,
	"val_apresentado" numeric(12, 2),
	"val_aprovado" numeric(12, 2),
	"situacao" text,
	"is_glosada" boolean GENERATED ALWAYS AS (situacao IS NOT NULL AND situacao <> '') STORED
);
--> statement-breakpoint
CREATE TABLE "producaosia"."profissionais_vinculos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "producaosia"."profissionais_vinculos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cod_cnes" text NOT NULL,
	"competencia" date NOT NULL,
	"profissional_nome" text NOT NULL,
	"cns" text NOT NULL,
	"cod_cbo" text NOT NULL,
	"ch_ambulatorial_sus" integer,
	"ch_hospitalar_sus" integer,
	"ch_outros" integer,
	"vinculo" text,
	"equipe_nome" text,
	"equipe_ine" text,
	"equipe_tipo" text
);
--> statement-breakpoint
ALTER TABLE "producaosia"."agrupamentos" ADD CONSTRAINT "fk_agrupamentos_procedimentos" FOREIGN KEY ("cod_proced") REFERENCES "producaosia"."procedimentos"("cod_proced") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "producaosia"."agrupamentos" ADD CONSTRAINT "fk_agrupamentos_cbo" FOREIGN KEY ("cod_cbo") REFERENCES "producaosia"."cbo"("cod_cbo") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "producaosia"."cbos_aps" ADD CONSTRAINT "fk_cbos_aps_cbo" FOREIGN KEY ("cod_cbo") REFERENCES "producaosia"."cbo"("cod_cbo") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "producaosia"."producao_sia" ADD CONSTRAINT "fk_producao_sia_estabelecimentos" FOREIGN KEY ("cod_cnes","competencia") REFERENCES "producaosia"."estabelecimentos"("cod_cnes","competencia") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "producaosia"."producao_sia" ADD CONSTRAINT "fk_producao_sia_procedimentos" FOREIGN KEY ("cod_proced") REFERENCES "producaosia"."procedimentos"("cod_proced") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "producaosia"."producao_sia" ADD CONSTRAINT "fk_producao_sia_cbo" FOREIGN KEY ("cod_cbo") REFERENCES "producaosia"."cbo"("cod_cbo") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "producaosia"."profissionais_vinculos" ADD CONSTRAINT "fk_profissionais_vinculos_estabelecimentos" FOREIGN KEY ("cod_cnes","competencia") REFERENCES "producaosia"."estabelecimentos"("cod_cnes","competencia") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "producaosia"."profissionais_vinculos" ADD CONSTRAINT "fk_profissionais_vinculos_cbo" FOREIGN KEY ("cod_cbo") REFERENCES "producaosia"."cbo"("cod_cbo") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_agrupamentos_proced_cbo" ON "producaosia"."agrupamentos" USING btree ("cod_proced","cod_cbo");--> statement-breakpoint
CREATE INDEX "idx_agrupamentos_cod_proced" ON "producaosia"."agrupamentos" USING btree ("cod_proced");--> statement-breakpoint
CREATE INDEX "idx_agrupamentos_cod_cbo" ON "producaosia"."agrupamentos" USING btree ("cod_cbo");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_estabelecimentos_cnes_comp" ON "producaosia"."estabelecimentos" USING btree ("cod_cnes","competencia");--> statement-breakpoint
CREATE INDEX "idx_estabelecimentos_cod_cnes" ON "producaosia"."estabelecimentos" USING btree ("cod_cnes");--> statement-breakpoint
CREATE INDEX "idx_estabelecimentos_competencia" ON "producaosia"."estabelecimentos" USING btree ("competencia");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_producao_sia" ON "producaosia"."producao_sia" USING btree ("cod_cnes","cod_proced","cod_cbo","competencia","situacao");--> statement-breakpoint
CREATE INDEX "idx_producao_sia_cnes_comp" ON "producaosia"."producao_sia" USING btree ("cod_cnes","competencia");--> statement-breakpoint
CREATE INDEX "idx_producao_sia_cod_proced" ON "producaosia"."producao_sia" USING btree ("cod_proced");--> statement-breakpoint
CREATE INDEX "idx_producao_sia_cod_cbo" ON "producaosia"."producao_sia" USING btree ("cod_cbo");--> statement-breakpoint
CREATE INDEX "idx_producao_sia_competencia" ON "producaosia"."producao_sia" USING btree ("competencia");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_profissionais_vinculos" ON "producaosia"."profissionais_vinculos" USING btree ("cod_cnes","cod_cbo","cns","competencia");--> statement-breakpoint
CREATE INDEX "idx_profissionais_vinculos_cnes_comp" ON "producaosia"."profissionais_vinculos" USING btree ("cod_cnes","competencia");--> statement-breakpoint
CREATE INDEX "idx_profissionais_vinculos_cns" ON "producaosia"."profissionais_vinculos" USING btree ("cns");--> statement-breakpoint
CREATE INDEX "idx_profissionais_vinculos_cod_cbo" ON "producaosia"."profissionais_vinculos" USING btree ("cod_cbo");